declare module 'lucide-react' {
  import { ComponentType, SVGProps } from 'react';
  export type IconProps = SVGProps<SVGSVGElement> & {
    size?: string | number;
    absoluteStrokeWidth?: boolean;
  };
  export type Icon = ComponentType<IconProps>;
  export const Sprout: Icon;
  export const Camera: Icon;
  export const Upload: Icon;
  export const Heart: Icon;
  export const AlertTriangle: Icon;
  export const CheckCircle: Icon;
  export const Settings: Icon;
  export const Users: Icon;
  export const FileText: Icon;
  export const CloudSun: Icon;
  export const User: Icon;
  export const LogOut: Icon;
  export const Search: Icon;
  export const Plus: Icon;
  export const Loader2: Icon;
  export const X: Icon;
  export const Send: Icon;
  export const ChevronRight: Icon;
  export const Check: Icon;
  export const BookOpen: Icon;
  export const FileDown: Icon;
  export const MessageSquare: Icon;
  export const Award: Icon;
  export const Clock: Icon;
  export const Thermometer: Icon;
  export const Droplets: Icon;
  export const Wind: Icon;
  export const MapPin: Icon;
  export const TrendingUp: Icon;
  export const Bell: Icon;
  export const Sliders: Icon;
  export const Sparkles: Icon;
  export const Eye: Icon;
  export const EyeOff: Icon;
  export const ShieldCheck: Icon;
  export const KeyRound: Icon;
  export const ArrowLeft: Icon;
  export const RefreshCw: Icon;
  export const Mail: Icon;
  export const Trash: Icon;
  export const Trash2: Icon;
  // New role dashboards (Commercial Farmer / Nursery Operator)
  export const Map: Icon;
  export const ChartLine: Icon;
  export const ClipboardList: Icon;
  export const Boxes: Icon;
  export const Truck: Icon;
  export const ChartPie: Icon;
  export const Building2: Icon;
  export const ChartBar: Icon;
  export const UsersRound: Icon;
  export const FileCheck: Icon;
  export const Minus: Icon;
  export const TrendingDown: Icon;
  export const DollarSign: Icon;
  export const ArrowRight: Icon;
  export const ShieldX: Icon;
  export const CalendarClock: Icon;
  export const ArrowDownAZ: Icon;
  export const ArrowUpAZ: Icon;
  export const Copy: Icon;
  export const CheckCircle2: Icon;
  export const ChevronDown: Icon;
  export const ChevronUp: Icon;
  export const Link2: Icon;
  export const Unlink: Icon;
  // Fallback for other icons if needed
  const icons: { [key: string]: Icon };
  export default icons;
}
